### ISSUE TITLE
succeed in compiling CUDA_extension but failed in running python code

### ISSUE THREAD

**Issue by zzzlxhhh** [PASSIONLab/CAGNET#10]
I have created a similar environment to reproduce the results in the CAGNET paper.
My environment is:
`
torch-1.4.0
torch-cluster-1.4.5
torch-geometric-1.3.2
torch-scatter-1.4.0
torch-sparse-0.4.3
torchvision-0.5.0
CUDA10.1
python-3.6.10
 `
You can notice that only the version of pytorch is different from yours. I succeeded in building `sparse-extension`.  Then I run `python gcn_distr_15d.py --graphname=Reddit --download=True`. It reports :
`Traceback (most recent call last):
  File "gcn_distr_15d.py", line 27, in <module>
    from sparse_coo_tensor_cpp import sparse_coo_tensor_gpu, spmm_gpu
ImportError: /root/miniconda3/envs/cagnet/lib/python3.6/site-packages/sparse_coo_tensor_cpp-0.0.0-py3.6-linux-x86_64.egg/sparse_coo_tensor_cpp.cpython-36m-x86_64-linux-gnu.so: undefined symbol: cusparseSpMM_bufferSize`

It's quite  a strange error. It would be nice if you can give some suggestions to solve my problem.

**Comment by zzzlxhhh** [comment]
I found the root of this issue that CUDA10.1.105 does not support the above functions in cusparse. cuda_10.1.243 and cuda_10.1.168 are supposed to be used instead. 

And, it would be helpful if you can give the python command to run training in a single-node-multi-GPU machine.

**Comment by zzzlxhhh** [comment]
> I found the root of this issue that CUDA10.1.105 does not support the above functions in cusparse. cuda_10.1.243 and cuda_10.1.168 are supposed to be used instead.
> 
> And, it would be helpful if you can give the python command to run training in a single-node-multi-GPU machine.

OK! I found the python command: `python -m torch.distributed.launch --nproc_per_node=4 gcn_distr_15d.py --accperrank=4 --epochs=100 --graphname=Reddit --timing=False --midlayer=16 --runcount=1 --replication=2`

**Comment by alokpathy** [comment]
That's interesting, thanks for figuring this out and letting me know! I've updated the README to point out the specific CUDA version needed.

**Comment by alokpathy** [comment]
With 2 GPUs the largest value of $c$ is 1. In general, $c^2$ must perfectly divide $p$.

**Comment by zzzlxhhh** [comment]
Does it mean that 1.5d with $c=1$ has the same computing process as 1d with 2GPUs ?

**Comment by alokpathy** [comment]
Yes exactly, the 1.5D algorithm without replication (i.e. c=1) is exactly the same as the 1D algorithm
