### ISSUE TITLE
compile error: ‘THCState_getCurrentSparseHandle’ was not declared in this scope

### ISSUE THREAD

**Issue by chenxuhao** [PASSIONLab/CAGNET#5]
Hello,

I got this error when compiling it:

$ python setup.py install
running install
running bdist_egg
running egg_info
writing sparse_coo_tensor_cpp.egg-info/PKG-INFO
writing dependency_links to sparse_coo_tensor_cpp.egg-info/dependency_links.txt
writing top-level names to sparse_coo_tensor_cpp.egg-info/top_level.txt
reading manifest file 'sparse_coo_tensor_cpp.egg-info/SOURCES.txt'
writing manifest file 'sparse_coo_tensor_cpp.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_ext
building 'sparse_coo_tensor_cpp' extension
gcc -pthread -B /pylon5/ci560jp/xhchen/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/pylon5/ci560jp/xhchen/anaconda3/lib/python3.7/site-packages/torch/include -I/pylon5/ci560jp/xhchen/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/pylon5/ci560jp/xhchen/anaconda3/lib/python3.7/site-packages/torch/include/TH -I/pylon5/ci560jp/xhchen/anaconda3/lib/python3.7/site-packages/torch/include/THC -I/pylon5/ci560jp/xhchen/anaconda3/include/python3.7m -c sparse_coo_tensor.cpp -o build/temp.linux-x86_64-3.7/sparse_coo_tensor.o -lcusparse -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=sparse_coo_tensor_cpp -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
sparse_coo_tensor.cpp: In function ‘void spmm_gpu(const at::Tensor&, const at::Tensor&, const at::Tensor&, int32_t, int32_t, at::Tensor&, at::Tensor&)’:
sparse_coo_tensor.cpp:125:19: error: ‘THCState_getCurrentSparseHandle’ was not declared in this scope
     auto handle = THCState_getCurrentSparseHandle(state);
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
sparse_coo_tensor.cpp:125:19: note: suggested alternative: ‘THCState_getCurrentStream’
     auto handle = THCState_getCurrentSparseHandle(state);
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                   THCState_getCurrentStream

Any idea what is wrong?

Best,
Xuhao Chen
https://chenxuhao.github.io/

**Comment by alokpathy** [comment]
It seems like `THCState` functions may be deprecated now (according to [this](https://stackoverflow.com/questions/55919123/cuda-for-pytorch-cuda-c-stream-and-state)). Are you using a newer version of pytorch?

I've pushed a new `cuda-context-issue` branch that replaces that function call. Could you let me know if that works, or try using pytorch 1.3.1?

**Comment by chenxuhao** [comment]
> It seems like `THCState` functions may be deprecated now (according to [this](https://stackoverflow.com/questions/55919123/cuda-for-pytorch-cuda-c-stream-and-state)). Are you using a newer version of pytorch?
> 
> I've pushed a new `cuda-context-issue` branch that replaces that function call. Could you let me know if that works, or try using pytorch 1.3.1?

Yes, this works! Thank you so much!

When I try to run it, I find that I don't have ddlrun.
So I try to run it like this (on a single host):

export RANK=1
export WORLD_SIZE=1
export MASTER_PORT=1234
export MASTER_ADDR=$(echo $LSB_MCPU_HOSTS | cut -d " " -f 3)
python gcn_distr_15d.py --accperrank=1 --epochs=100 --graphname=Reddit --timing=False --midlayer=16 --runcount=1 --replication=2


I got this:
Namespace(accperrank=1, accuracy=None, activations=None, download=None, epochs=100, graphname='Reddit', local_rank=None, midlayer=16, normalization=None, replication=2, runcount=1, timing='False')
Arguments: epochs: 100 graph: Reddit timing: False mid: 16 norm: False act: False acc: False runs: 1 rep: 2
gpu049.pvt.bridges.psc.edu
Traceback (most recent call last):
  File "gcn_distr_15d.py", line 856, in <module>
    print(main())
  File "gcn_distr_15d.py", line 726, in main
    dist.init_process_group(backend='nccl')
  File "/pylon5/ci560jp/xhchen/anaconda3/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 397, in init_process_group
    store, rank, world_size = next(rendezvous_iterator)
  File "/pylon5/ci560jp/xhchen/anaconda3/lib/python3.7/site-packages/torch/distributed/rendezvous.py", line 168, in _env_rendezvous_handler
    store = TCPStore(master_addr, master_port, world_size, start_daemon)
ValueError: host not found: Name or service not known


I think the MASTER_ADDR is not set correctly, since LSB_MCPU_HOSTS is empty.
So what is the MASTER_ADDR supposed to be? localhost? 127.0.0.1?

Thanks,
Xuhao

**Comment by ranzhejiang** [comment]
> > It seems like `THCState` functions may be deprecated now (according to [this](https://stackoverflow.com/questions/55919123/cuda-for-pytorch-cuda-c-stream-and-state)). Are you using a newer version of pytorch?
> > I've pushed a new `cuda-context-issue` branch that replaces that function call. Could you let me know if that works, or try using pytorch 1.3.1?
> 
> Yes, this works! Thank you so much!
> 
> When I try to run it, I find that I don't have ddlrun.
> So I try to run it like this (on a single host):
> 
> export RANK=1
> export WORLD_SIZE=1
> export MASTER_PORT=1234
> export MASTER_ADDR=$(echo $LSB_MCPU_HOSTS | cut -d " " -f 3)
> python gcn_distr_15d.py --accperrank=1 --epochs=100 --graphname=Reddit --timing=False --midlayer=16 --runcount=1 --replication=2
> 
> I got this:
> Namespace(accperrank=1, accuracy=None, activations=None, download=None, epochs=100, graphname='Reddit', local_rank=None, midlayer=16, normalization=None, replication=2, runcount=1, timing='False')
> Arguments: epochs: 100 graph: Reddit timing: False mid: 16 norm: False act: False acc: False runs: 1 rep: 2
> gpu049.pvt.bridges.psc.edu
> Traceback (most recent call last):
> File "gcn_distr_15d.py", line 856, in
> print(main())
> File "gcn_distr_15d.py", line 726, in main
> dist.init_process_group(backend='nccl')
> File "/pylon5/ci560jp/xhchen/anaconda3/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 397, in init_process_group
> store, rank, world_size = next(rendezvous_iterator)
> File "/pylon5/ci560jp/xhchen/anaconda3/lib/python3.7/site-packages/torch/distributed/rendezvous.py", line 168, in _env_rendezvous_handler
> store = TCPStore(master_addr, master_port, world_size, start_daemon)
> ValueError: host not found: Name or service not known
> 
> I think the MASTER_ADDR is not set correctly, since LSB_MCPU_HOSTS is empty.
> So what is the MASTER_ADDR supposed to be? localhost? 127.0.0.1?
> 
> Thanks,
> Xuhao

try it with the command python -m torch.distributed.launch --nproc_per_node=4 gcn_distr_15d.py --accperrank=4 --epochs=100 --graphname=Reddit --timing=False --midlayer=16 --runcount=1 --replication=2

**Comment by alokpathy** [comment]
Glad that branch worked!

So two things here:

1) if you don't have `ddlrun` and since you say you're running on a single node, I would recommend what @ranzhejiang suggested. This will run the code on a single node without needing anything from the IBM toolchain (e.g. `ddlrun` or `$LSB_MCPU_HOSTS`. You can also refer to the documentation for `torch.distributed.launch` for help [here](https://github.com/pytorch/pytorch/blob/master/torch/distributed/launch.py).

2) For future reference, `$MASTER_ADDR` should be the hostname for the rank 0 node. In a single node case, this would  just be localhost, yes.

Let me know if you're still having issues

**Comment by alokpathy** [comment]
Hey Xuhao, just checking to see if things work for you now and I could close the issue. Let me know if you have anything else

**Comment by chenxuhao** [comment]
> Hey Xuhao, just checking to see if things work for you now and I could close the issue. Let me know if you have anything else

Hi Alok, yes I got it work and thank you very much!

**Comment by alokpathy** [comment]
Great :)

**Comment by alokpathy** [comment]
Following up on this to include a sample command if you'd like to run CAGNET with SLURM, 

`srun --ntasks-per-node=2 python gcn_distr.py --accperrank=2 --epochs=100 --graphname=Cora --timing=True --midlayer=16 --runcount=1`
