### ISSUE TITLE
Which branch is proper to use when CUDA_VERSION>11.0

### ISSUE THREAD

**Issue by zzzlxhhh** [PASSIONLab/CAGNET#9]
Hi!
   I'm trying to reproduce your brilliant works on our environment. However, we encounters several compilation problems due to incompatible dependency libraries. We are using CUDA11.4. It would be nice if you can give some suggestions on which branch of your codebase should be used for easier reproduction. So far we tried your newest branch `trackml`, but with compilation error as `fatal error: nsparse_asm.h: No such file or directory`

**Comment by alokpathy** [comment]
Sorry for the late response. trackml is still a development branch. If you're trying to reproduce results from the "Reducing Communication in GNN Training" paper, you should use the master branch. Feel free to let me know if you run into issues running that code!

**Comment by zzzlxhhh** [comment]
Thanks for your kindly advice! We will try to reproduce the results in a docker with a similar environment as yours.
